TRAIN_DATA = [
  ("Tell me the Air Quality Index for Los Angeles on January 10, 2023.", {"entities": [("Air Quality Index", "AQ_INDEX"), ("Los Angeles", "LOCATION"), ("January 10, 2023", "PAST_TIME")]}),
    ("What is the dominant pollutant in New York City?", {"entities": [("dominant pollutant", "DOMINANT_POLLUTANT"), ("New York City", "LOCATION")]}),
    ("Give me the air quality for Tokyo on March 15, 2022.", {"entities": [("air quality", "AQ_INDEX"), ("Tokyo", "LOCATION"), ("March 15, 2022", "PAST_TIME")]}),
    ("What was the AQI in Berlin on February 20, 2021, at 5 PM?", {"entities": [("AQI", "AQ_INDEX"), ("Berlin", "LOCATION"), ("February 20, 2021, at 5 PM", "PAST_TIME")]}),
    ("Provide the air quality index for Mumbai.", {"entities": [("air quality index", "AQ_INDEX"), ("Mumbai", "LOCATION")]}),
    ("What are the health recommendations for lung disease patients in Paris?", {"entities": [("health recommendations", "HEALTH_RECOMMENDATIONS"), ("lung disease patients", "LUNG_DISEASES"), ("Paris", "LOCATION")]}),
    ("Show me the dominant pollutant in London on April 2, 2022.", {"entities": [("dominant pollutant", "DOMINANT_POLLUTANT"), ("London", "LOCATION"), ("April 2, 2022", "PAST_TIME")]}),
    ("Tell me the AQI for Beijing.", {"entities": [("AQI", "AQ_INDEX"), ("Beijing", "LOCATION")]}),
    ("What was the air quality in Sydney on July 14, 2020, at 9 AM?", {"entities": [("air quality", "AQ_INDEX"), ("Sydney", "LOCATION"), ("July 14, 2020, at 9 AM", "PAST_TIME")]}),
    ("Give me the dominant pollutant in Cairo.", {"entities": [("dominant pollutant", "DOMINANT_POLLUTANT"), ("Cairo", "LOCATION")]}),
    ("What are the health recommendations for athletes in Rio de Janeiro?", {"entities": [("health recommendations", "HEALTH_RECOMMENDATIONS"), ("athletes", "ATHLETES"), ("Rio de Janeiro", "LOCATION")]}),
    ("Tell me the Air Quality Index for Seoul.", {"entities": [("Air Quality Index", "AQ_INDEX"), ("Seoul", "LOCATION")]}),
    ("What is the air quality in Mexico City?", {"entities": [("air quality", "AQ_INDEX"), ("Mexico City", "LOCATION")]}),
    ("Show me the AQI in Buenos Aires on May 25, 2021.", {"entities": [("AQI", "AQ_INDEX"), ("Buenos Aires", "LOCATION"), ("May 25, 2021", "PAST_TIME")]}),
    ("Give me the dominant pollutant in Singapore on August 30, 2023.", {"entities": [("dominant pollutant", "DOMINANT_POLLUTANT"), ("Singapore", "LOCATION"), ("August 30, 2023", "PAST_TIME")]}),
    ("What was the air quality index in Hong Kong last week?", {"entities": [("air quality index", "AQ_INDEX"), ("Hong Kong", "LOCATION"), ("last week", "PAST_TIME")]}),
    ("Provide the AQI for San Francisco.", {"entities": [("AQI", "AQ_INDEX"), ("San Francisco", "LOCATION")]}),
    ("What is the dominant pollutant in Dubai?", {"entities": [("dominant pollutant", "DOMINANT_POLLUTANT"), ("Dubai", "LOCATION")]}),
    ("Tell me the air quality for Cape Town on March 1, 2022.", {"entities": [("air quality", "AQ_INDEX"), ("Cape Town", "LOCATION"), ("March 1, 2022", "PAST_TIME")]}),
    ("What is the Air Quality Index in Moscow?", {"entities": [("Air Quality Index", "AQ_INDEX"), ("Moscow", "LOCATION")]}),
    ("Give me the health recommendations for children in Jakarta.", {"entities": [("health recommendations", "HEALTH_RECOMMENDATIONS"), ("children", "CHILDREN"), ("Jakarta", "LOCATION")]}),
    ("Show me the AQI for Toronto on June 5, 2023.", {"entities": [("AQI", "AQ_INDEX"), ("Toronto", "LOCATION"), ("June 5, 2023", "PAST_TIME")]}),
    ("What is the dominant pollutant in Nairobi?", {"entities": [("dominant pollutant", "DOMINANT_POLLUTANT"), ("Nairobi", "LOCATION")]}),
    ("Tell me the air quality index in Madrid.", {"entities": [("air quality index", "AQ_INDEX"), ("Madrid", "LOCATION")]}),
    ("What was the air quality in Bangkok on December 18, 2021?", {"entities": [("air quality", "AQ_INDEX"), ("Bangkok", "LOCATION"), ("December 18, 2021", "PAST_TIME")]}),
    ("Provide the dominant pollutant in Lagos.", {"entities": [("dominant pollutant", "DOMINANT_POLLUTANT"), ("Lagos", "LOCATION")]}),
    ("What are the health recommendations for elderly people in New York?", {"entities": [("health recommendations", "HEALTH_RECOMMENDATIONS"), ("elderly people", "ELDERLY"), ("New York", "LOCATION")]}),
    ("Show me the air quality index for Berlin on November 2, 2022.", {"entities": [("air quality index", "AQ_INDEX"), ("Berlin", "LOCATION"), ("November 2, 2022", "PAST_TIME")]}),
    ("Tell me the AQI in Tokyo for March 2023.", {"entities": [("AQI", "AQ_INDEX"), ("Tokyo", "LOCATION"), ("March 2023", "PAST_TIME")]}),
    ("Give me the dominant pollutant in Toronto.", {"entities": [("dominant pollutant", "DOMINANT_POLLUTANT"), ("Toronto", "LOCATION")]}),
    ("What is the air quality in Buenos Aires?", {"entities": [("air quality", "AQ_INDEX"), ("Buenos Aires", "LOCATION")]}),
    ("What was the AQI in Paris on May 8, 2021?", {"entities": [("AQI", "AQ_INDEX"), ("Paris", "LOCATION"), ("May 8, 2021", "PAST_TIME")]}),
    ("Provide the air quality index in Singapore.", {"entities": [("air quality index", "AQ_INDEX"), ("Singapore", "LOCATION")]}),
    ("What is the dominant pollutant in Los Angeles?", {"entities": [("dominant pollutant", "DOMINANT_POLLUTANT"), ("Los Angeles", "LOCATION")]}),
    ("Tell me the air quality for Johannesburg.", {"entities": [("air quality", "AQ_INDEX"), ("Johannesburg", "LOCATION")]}),
    ("Show me the AQI in Madrid on October 15, 2020.", {"entities": [("AQI", "AQ_INDEX"), ("Madrid", "LOCATION"), ("October 15, 2020", "PAST_TIME")]}),
    ("Give me the dominant pollutant in Cairo on June 10, 2023.", {"entities": [("dominant pollutant", "DOMINANT_POLLUTANT"), ("Cairo", "LOCATION"), ("June 10, 2023", "PAST_TIME")]}),
    ("What is the air quality index in Shanghai?", {"entities": [("air quality index", "AQ_INDEX"), ("Shanghai", "LOCATION")]}),
    ("Tell me the AQI for Nairobi.", {"entities": [("AQI", "AQ_INDEX"), ("Nairobi", "LOCATION")]}),
    ("What are the health recommendations for people with heart disease in Tokyo?", {"entities": [("health recommendations", "HEALTH_RECOMMENDATIONS"), ("people with heart disease", "HEART_DISEASES"), ("Tokyo", "LOCATION")]}),
    ("Show me the dominant pollutant in Sydney.", {"entities": [("dominant pollutant", "DOMINANT_POLLUTANT"), ("Sydney", "LOCATION")]}),
    ("What is the air quality in Lima?", {"entities": [("air quality", "AQ_INDEX"), ("Lima", "LOCATION")]}),
     ("Show me the heatmap for the World.", {"entities": [("World", "LOCATION")]}),
    ("Can I get the heatmap for Europe?", {"entities": [("Europe", "LOCATION")]}),
    ("Generate a heatmap for Asia.", {"entities": [("Asia", "LOCATION")]}),
    ("Provide the heatmap for North America.", {"entities": [("North America", "LOCATION")]}),
    ("What does the heatmap for South America look like?", {"entities": [("South America", "LOCATION")]}),
    ("Show the heatmap for Oceania.", {"entities": [("Oceania", "LOCATION")]}),
    ("Give me the heatmap for Australia.", {"entities": [("Australia", "LOCATION")]}),
    ("What is the heatmap for Africa?", {"entities": [("Africa", "LOCATION")]}),
    ("Display the World heatmap.", {"entities": [("World", "LOCATION")]}),
    ("Can I see the heatmap for Europe?", {"entities": [("Europe", "LOCATION")]}),
    ("Show me the Asia heatmap.", {"entities": [("Asia", "LOCATION")]}),
    ("Give me the heatmap for North America.", {"entities": [("North America", "LOCATION")]}),
    ("Generate the South America heatmap.", {"entities": [("South America", "LOCATION")]}),
    ("What is the heatmap for Oceania?", {"entities": [("Oceania", "LOCATION")]}),
    ("Show me the heatmap for Australia.", {"entities": [("Australia", "LOCATION")]}),
    ("Display the heatmap for Africa.", {"entities": [("Africa", "LOCATION")]}),
    ("Can you show the heatmap for the World?", {"entities": [("World", "LOCATION")]}),
    ("Provide the heatmap for Europe.", {"entities": [("Europe", "LOCATION")]}),
    ("What does the heatmap for Asia look like?", {"entities": [("Asia", "LOCATION")]}),
    ("Show me the heatmap for North America.", {"entities": [("North America", "LOCATION")]}),
    ("Give me the South America heatmap.", {"entities": [("South America", "LOCATION")]}),
    ("Display the heatmap for Oceania.", {"entities": [("Oceania", "LOCATION")]}),
    ("Can I get the heatmap for Australia?", {"entities": [("Australia", "LOCATION")]}),
    ("What is the heatmap for Africa?", {"entities": [("Africa", "LOCATION")]}),
    ("Show the heatmap for the World.", {"entities": [("World", "LOCATION")]}),
    ("Give me the heatmap for Europe.", {"entities": [("Europe", "LOCATION")]}),
    ("Display the heatmap for Asia.", {"entities": [("Asia", "LOCATION")]}),
    ("Generate the North America heatmap.", {"entities": [("North America", "LOCATION")]}),
    ("What does the South America heatmap look like?", {"entities": [("South America", "LOCATION")]}),
    ("Show me the heatmap for Oceania.", {"entities": [("Oceania", "LOCATION")]}),
    ("Provide the heatmap for Australia.", {"entities": [("Australia", "LOCATION")]}),
    ("Can you show the heatmap for Africa?", {"entities": [("Africa", "LOCATION")]}),
    ("What is the heatmap for the World?", {"entities": [("World", "LOCATION")]}),
    ("Show me the Europe heatmap.", {"entities": [("Europe", "LOCATION")]}),
    ("Give me the heatmap for Asia.", {"entities": [("Asia", "LOCATION")]}),
    ("Display the heatmap for North America.", {"entities": [("North America", "LOCATION")]}),
    ("What does the heatmap for South America look like?", {"entities": [("South America", "LOCATION")]}),
    ("Provide the heatmap for Oceania.", {"entities": [("Oceania", "LOCATION")]}),
    ("Show me the Australia heatmap.", {"entities": [("Australia", "LOCATION")]}),
    ("Can I see the heatmap for Africa?", {"entities": [("Africa", "LOCATION")]}),
    ("Give me the World heatmap.", {"entities": [("World", "LOCATION")]}),
    ("What is the heatmap for Europe?", {"entities": [("Europe", "LOCATION")]}),
    ("Show the Asia heatmap.", {"entities": [("Asia", "LOCATION")]}),
    ("Display the heatmap for North America.", {"entities": [("North America", "LOCATION")]}),
    ("Generate the South America heatmap.", {"entities": [("South America", "LOCATION")]}),
    ("What is the heatmap for Oceania?", {"entities": [("Oceania", "LOCATION")]}),
    ("Show me the heatmap for Australia.", {"entities": [("Australia", "LOCATION")]}),
    ("Provide the heatmap for Africa.", {"entities": [("Africa", "LOCATION")]}),
    ("Show the heatmap for the World.", {"entities": [("World", "LOCATION")]}),


]